package terraform.gcp.security.cloud_bigtable.google_bigtable_instance.vars

variables := {
  "friendly_resource_name": "Cloud Bigtable Instance",
  "resource_type": "google_bigtable_instance",
  "resource_value_name": "name",
  "attribute_path": ["labels"],

  "required_labels": [
    { "key": "label1", "equals": "v1" },
    { "key": "label2", "equals": "v2" },
    { "key": "label3", "equals": "v3" },
    { "key": "label4", "equals": "v4" },
    { "key": "label5", "equals": "v5" },
    { "key": "label6", "equals": "v6" },
    { "key": "label7", "equals": "v7" },
    { "key": "label8", "equals": "v8" },
    { "key": "label9", "equals": "v9" },
    { "key": "label10", "equals": "v10" },

    { "key": "label11", "equals": "v11" },
    { "key": "label12", "equals": "v12" },
    { "key": "label13", "equals": "v13" },
    { "key": "label14", "equals": "v14" },
    { "key": "label15", "equals": "v15" },
    { "key": "label16", "equals": "v16" },
    { "key": "label17", "equals": "v17" },
    { "key": "label18", "equals": "v18" },
    { "key": "label19", "equals": "v19" },
    { "key": "label20", "equals": "v20" },

    { "key": "label21", "equals": "v21" },
    { "key": "label22", "equals": "v22" },
    { "key": "label23", "equals": "v23" },
    { "key": "label24", "equals": "v24" },
    { "key": "label25", "equals": "v25" },
    { "key": "label26", "equals": "v26" },
    { "key": "label27", "equals": "v27" },
    { "key": "label28", "equals": "v28" },
    { "key": "label29", "equals": "v29" },
    { "key": "label30", "equals": "v30" },

    { "key": "label31", "equals": "v31" },
    { "key": "label32", "equals": "v32" },
    { "key": "label33", "equals": "v33" },
    { "key": "label34", "equals": "v34" },
    { "key": "label35", "equals": "v35" },
    { "key": "label36", "equals": "v36" },
    { "key": "label37", "equals": "v37" },
    { "key": "label38", "equals": "v38" },
    { "key": "label39", "equals": "v39" },
    { "key": "label40", "equals": "v40" },

    { "key": "label41", "equals": "v41" },
    { "key": "label42", "equals": "v42" },
    { "key": "label43", "equals": "v43" },
    { "key": "label44", "equals": "v44" },
    { "key": "label45", "equals": "v45" },
    { "key": "label46", "equals": "v46" },
    { "key": "label47", "equals": "v47" },
    { "key": "label48", "equals": "v48" },
    { "key": "label49", "equals": "v49" },
    { "key": "label50", "equals": "v50" },

    { "key": "label51", "equals": "v51" },
    { "key": "label52", "equals": "v52" },
    { "key": "label53", "equals": "v53" },
    { "key": "label54", "equals": "v54" },
    { "key": "label55", "equals": "v55" },
    { "key": "label56", "equals": "v56" },
    { "key": "label57", "equals": "v57" },
    { "key": "label58", "equals": "v58" },
    { "key": "label59", "equals": "v59" },
    { "key": "label60", "equals": "v60" },

    { "key": "label61", "equals": "v61" },
    { "key": "label62", "equals": "v62" },
    { "key": "label63", "equals": "v63" },
    { "key": "label64", "equals": "v64" },
    { "key": "label65", "equals": "v65" },
    { "key": "label66", "equals": "v66" },
    { "key": "label67", "equals": "v67" },
    { "key": "label68", "equals": "v68" },
    { "key": "label69", "equals": "v69" },
    { "key": "label70", "equals": "v70" },

    { "key": "label71", "equals": "v71" },
    { "key": "label72", "equals": "v72" },
    { "key": "label73", "equals": "v73" },
    { "key": "label74", "equals": "v74" },
    { "key": "label75", "equals": "v75" },
    { "key": "label76", "equals": "v76" },
    { "key": "label77", "equals": "v77" },
    { "key": "label78", "equals": "v78" },
    { "key": "label79", "equals": "v79" },
    { "key": "label80", "equals": "v80" },

    { "key": "label81", "equals": "v81" },
    { "key": "label82", "equals": "v82" },
    { "key": "label83", "equals": "v83" },
    { "key": "label84", "equals": "v84" },
    { "key": "label85", "equals": "v85" },
    { "key": "label86", "equals": "v86" },
    { "key": "label87", "equals": "v87" },
    { "key": "label88", "equals": "v88" },
    { "key": "label89", "equals": "v89" },
    { "key": "label90", "equals": "v90" },

    { "key": "label91", "equals": "v91" },
    { "key": "label92", "equals": "v92" },
    { "key": "label93", "equals": "v93" },
    { "key": "label94", "equals": "v94" },
    { "key": "label95", "equals": "v95" },
    { "key": "label96", "equals": "v96" },
    { "key": "label97", "equals": "v97" },
    { "key": "label98", "equals": "v98" },
    { "key": "label99", "equals": "v99" },
    { "key": "label100", "equals": "v100" }
  ]
}
